spring:
  application:
    name: chatgpt-client
  codec:
    max-in-memory-size: 16MB

  r2dbc:
    url: r2dbc:h2:mem:///chatgpt_client;SCHEMA=PUBLIC
    username: sa
    password:
    pool:
      initial-size: 10
      max-size: 20

  # Keep H2 console for development
  h2:
    console:
      enabled: true
      path: /h2-console

  # R2DBC doesn't use JPA, but we can configure SQL initialization
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    com.chatgpt.client: DEBUG
    org.springframework.web: DEBUG
    org.springframework.r2dbc: DEBUG

server:
  port: 8080

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
  default:
    model: deepseek/deepseek-r1-0528:free
    max-tokens: 4000
    temperature: 0.7
  credits:
    initial: 10.0
